// AUTO-GENERATED by tools/gen_opcode_handlers.py from the protocol atlas. DO NOT EDIT.
// 568 server->client extension opcodes (>= 0x51F).
#pragma once

#include <cstdint>

namespace AscOpcodes
{
    // Registers a parsing handler for every opcode in the generated table. Call this BEFORE the
    // hand-written services register theirs, so a real implementation always wins the map slot.
    void RegisterAll();

    const char* NameOf(uint32_t opcode);        // atlas name, or nullptr
    const char* LayoutStateOf(uint32_t opcode); // proven | named | widths | empty | unknown
    uint32_t Count();
}
