// AUTO-GENERATED by scratchpad/gen_stubs.py -- do not hand-edit.
//
// Safe stubs for every Lua native the real Extensions.dll registers that this reconstruction has
// not implemented with real logic yet. Each stub is callable (so scripts that check `if C_X.Y then`
// or call it directly don't hit a hard Lua error) and pushes the SAME NUMBER of return values as the
// real handler's decompiled `return N;` (Lua CFunction convention), as plain nils -- existence and
// arity are real, the DATA is not. Source: E:\oniwow-artifacts\ghidra-ext\sym\namespaces.yaml +
// lua-bindings.yaml + out\bindings\*.c (per-binding decompile, RVA-addressed, build 2026-08-13).
//
// Real, hand-written implementations always win: this file only covers namespaces/globals NOT
// already registered in RealmInfo.cpp / AscRegistry.cpp (see HAND_IMPLEMENTED_* in the generator).
#include <Ascension/AscLua.hpp>
#include <Client/CDataStore.hpp>
#include <Client/ClientServices.hpp>
#include <Windows.h>
#include <Ascension/AscLog.hpp>

using namespace AscLua;

// ---- shared client-data helpers (used by the transcribed bindings below) ----------------
namespace
{
    const uint32_t kSpellDbc = 0xAD49D0;        // Spell.dbc container (ecx for 0x4CFD20)
    const uint32_t kSpellIconDbc = 0xAD488C;    // SpellIcon.dbc container
    const uint32_t kSpellRecordSize = 0x2A8;    // bytes 0x4CFD20 copies

    bool FetchSpellRecord(uint32_t spellId, void* out)
    {
        typedef int(__thiscall* GetRec_t)(void*, uint32_t, void*);
        return reinterpret_cast<GetRec_t>(0x4CFD20)(reinterpret_cast<void*>(kSpellDbc), spellId, out) != 0;
    }

    const uint32_t kChrClassesDbc = 0xAD3404;   // ChrClasses.dbc container (from FUN_100b13c0)

    // FUN_100b2470 / FUN_100b13c0, generalised: every DBC lookup in this client has the same shape --
    // container[+0x20][id - container[+0x10]], bounds at +0x0C (max) and +0x10 (min).
    uint32_t DbcRow(uint32_t container, uint32_t id)
    {
        uint32_t maxId = *reinterpret_cast<uint32_t*>(container + 0x0C);
        uint32_t minId = *reinterpret_cast<uint32_t*>(container + 0x10);
        uint32_t rows  = *reinterpret_cast<uint32_t*>(container + 0x20);
        if (!rows || id < minId || id > maxId)
            return 0;
        return *reinterpret_cast<uint32_t*>(rows + (id - minId) * 4);
    }

    const char* DbcRowString(uint32_t container, uint32_t id, uint32_t fieldOffset)
    {
        uint32_t row = DbcRow(container, id);
        return row ? *reinterpret_cast<const char**>(row + fieldOffset) : nullptr;
    }

    const char* SafeStr(const char* s) { return (s && *s) ? s : nullptr; }
}

// ---- SetCanSeeAppearances / SetLevelScaling -----------------------------------------------------
// The two character-creation toggles. Both were stubs, so the creator recorded the player's choice
// (NewCharacterSetupUtil stores it, then replays it on PLAYER_LOGIN) and then handed it to a no-op.
//
// Transcribed from ghidra-ext/out/bindings/{SetCanSeeAppearances,SetLevelScaling}.c. Both build a
// packet the same way the client does everywhere else (GenPacket / PutInt32 opcode / body /
// m_read = 0 / SendPacket / Release -- same shape as CustomLua::PortGraveyard upstream).
//
//   SetCanSeeAppearances(items, spells) -> CMSG 0x6A3, two u8 bodies, returns true.
//       Server side EXISTS: mod-ascension-compat handles CMSG_SET_CAN_SEE_APPEARANCES (0x06A3)
//       via HandleSetAppearanceVisibility, and reports state back with SMSG_CAN_SEE_APPEARANCES_INFO
//       (0x6A2), whose layout we already verified live.
//
//   SetLevelScaling(enabled) -> CMSG 0x667, one u32 body, no return values. The original gates on
//       the client action check first (FUN_10111ce0(0x11) -- action 17, Forbidden), so we do too.
//       Server side EXISTS, in a DIFFERENT module: mod-destiny-weaver owns CMSG_SET_LEVEL_SCALING
//       (0x0667) via DestinyWeaver::HandleClientLevelScalingPacket, reading a u32 and storing the
//       per-character choice in character_settings under "core.destiny_weaver". It is registered
//       both through AscensionCompatOpcodes::Claim and its own CanPacketReceiveEarly. Grepping only
//       AscensionCompat.cpp made it look absent -- this is a multi-module tree.
static int Asc_SetCanSeeAppearances(lua_State* L)
{
    const int8_t items  = lua_toboolean(L, 1) ? 1 : 0;
    const int8_t spells = lua_toboolean(L, 2) ? 1 : 0;

    CDataStore pkt{};
    CDataStore::GenPacket(&pkt);
    CDataStore::PutInt32(&pkt, 0x6A3);
    CDataStore::PutInt8(&pkt, items);
    CDataStore::PutInt8(&pkt, spells);
    pkt.m_read = 0;
    ClientServices::SendPacket(&pkt);
    CDataStore::Release(&pkt);

    AscLog::Printf("SetCanSeeAppearances(%d, %d) -> CMSG 0x6A3", items, spells);
    lua_pushboolean(L, 1);
    return 1;
}

static int Asc_SetLevelScaling(lua_State* L)
{
    // action 17 = Enum.UIActionType.Forbidden, the same gate CanPerformAction uses
    int allowed = 1;
    __try { allowed = reinterpret_cast<int(__cdecl*)(uint32_t)>(0x5191C0)(17); }
    __except (EXCEPTION_EXECUTE_HANDLER) { allowed = 1; }
    if (!allowed)
    {
        AscLog::Printf("SetLevelScaling: blocked by the client action gate");
        return 0;
    }

    const int32_t enabled = lua_toboolean(L, 1) ? 1 : 0;

    CDataStore pkt{};
    CDataStore::GenPacket(&pkt);
    CDataStore::PutInt32(&pkt, 0x667);
    CDataStore::PutInt32(&pkt, enabled);
    pkt.m_read = 0;
    ClientServices::SendPacket(&pkt);
    CDataStore::Release(&pkt);

    AscLog::Printf("SetLevelScaling(%d) -> CMSG 0x667", enabled);
    return 0;
}

int AscCA_GetAllEntries(struct lua_State* L);   // AscCharacterAdvancement.cpp

namespace AscStubs
{
static int Stub0(lua_State* L) {
    return 0;
}
// Returns an EMPTY TABLE rather than nil, for natives the UI immediately iterates. A nil there is
// a hard error (pairs/next on nil); an empty table lets the caller run with no data. Still a stub.
// Returns 0 rather than nil, for natives the UI uses as a NUMBER -- counts, maxima and
// progress values feeding `for i = 1, X()`, arithmetic or comparisons. nil there is a hard
// error ("'for' limit must be a number", "attempt to perform arithmetic on a nil value").
static int StubZero(lua_State* L) {
    lua_pushnumber(L, 0.0);
    return 1;
}
// Two zeros, for the min/max pair getters (e.g. Ascension_GetArenaRewardInfo feeding
// SetMinMaxValues, which rejects a nil max with a "Usage:" error).
static int StubZero2(lua_State* L) {
    lua_pushnumber(L, 0.0);
    lua_pushnumber(L, 0.0);
    return 2;
}
static int StubTable(lua_State* L) {
    lua_createtable(L, 0, 0);
    return 1;
}
static int Stub1(lua_State* L) {
    lua_checkstack(L, 1);
    lua_pushnil(L);
    return 1;
}
static int Stub2(lua_State* L) {
    lua_checkstack(L, 2);
    lua_pushnil(L);
    lua_pushnil(L);
    return 2;
}
static int Stub3(lua_State* L) {
    lua_checkstack(L, 3);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    return 3;
}
static int Stub4(lua_State* L) {
    lua_checkstack(L, 4);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    return 4;
}
static int Stub5(lua_State* L) {
    lua_checkstack(L, 5);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    return 5;
}
static int Stub6(lua_State* L) {
    lua_checkstack(L, 6);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    return 6;
}
static int Stub7(lua_State* L) {
    lua_checkstack(L, 7);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    return 7;
}
static int Stub8(lua_State* L) {
    lua_checkstack(L, 8);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    lua_pushnil(L);
    return 8;
}

static const AscLua::Reg C_AccountInfo_Stubs[] = {
    {"GetCharacterAtIndex", Stub1},
    {"GetGMLevel", StubZero},
    {"GetNumCharacters", Stub1},
    {"IsGM", Stub1},
    {"IsGuide", Stub1},
    {"IsNewcomer", Stub1},
};
static const AscLua::Reg C_Appearance_Stubs[] = {
    {"ApplyPendingAppearances", Stub1},
    {"CanApplyPendingAppearances", Stub2},
    {"CanSeeAppearances", Stub2},
    {"CanSetAppearance", Stub4},
    {"ClearInvalidPendingAppearances", Stub4},
    {"ClearPendingAppearance", Stub0},
    {"ClearPendingAppearances", Stub0},
    {"GetActiveDiscount", Stub3},
    {"GetAlternativeIDs", Stub1},
    {"GetAppearanceDetails", Stub1},
    {"GetAppearanceDisplayInfo", Stub6},
    {"GetAppearanceForCategory", Stub1},
    {"GetAppearanceItemSet", Stub1},
    {"GetAppearanceWebURL", Stub2},
    {"GetCreatureDisplayItems", Stub1},
    {"GetEtherealBazaarWebURL", Stub2},
    {"GetItemAppearanceID", Stub1},
    {"GetItemSetAppearanceID", Stub1},
    {"GetPendingAppearance", Stub1},
    {"HasPendingAppearances", Stub1},
    {"IsEtherealBazaarAppearance", Stub1},
    {"IsTransmogable", Stub1},
    {"SetCanSeeAppearances", Asc_SetCanSeeAppearances},
    {"SetPendingAppearance", Stub1},
};
static const AscLua::Reg C_AppearanceCollection_Stubs[] = {
    {"ApplyCategoryFilter", Stub0},
    {"CollectItemAppearance", Stub1},
    {"GetAppearanceTypes", StubTable},
    {"GetAvailableChapters", Stub1},
    {"GetAvailableSeasons", Stub1},
    {"GetCategoriesForType", Stub1},
    {"GetCategoryAppearances", Stub1},
    {"GetCategoryInfo", Stub3},
    {"GetCategoryMaxPages", Stub1},
    {"GetCollectedCount", Stub2},
    {"GetSeasonalItems", Stub1},
    {"IsAppearanceCollected", Stub1},
};
static const AscLua::Reg C_AppearanceOutfit_Stubs[] = {
    {"DeleteOutfit", Stub1},
    {"GetAppearanceOutfits", Stub1},
    {"GetCurrentOutfitName", Stub1},
    {"GetOutfitInfo", StubTable},
    {"SaveOutfit", Stub1},
    {"SetPendingOutfit", Stub0},
};
static const AscLua::Reg C_AssetQueryService_Stubs[] = {
    {"TryCacheCreature", Stub1},
    {"TryCacheItem", Stub1},
    {"TryCacheQuest", Stub1},
};
static const AscLua::Reg C_Aura_Stubs[] = {
    {"GetArmorPenetrationModifier", Stub1},
    {"UnitHasAura", Stub1},
};
static const AscLua::Reg C_BugTracker_Stubs[] = {
    {"ClearReport", Stub0},
    {"CreateBugReport", Stub1},
    {"GetReportCategory", Stub1},
    {"GetReportDescription", Stub1},
    {"GetReportPriority", Stub1},
    {"GetReportTitle", Stub1},
    {"IsReportPublic", Stub1},
    {"SetReportCategory", Stub1},
    {"SetReportDescription", Stub1},
    {"SetReportPriority", Stub1},
    {"SetReportPublic", Stub1},
    {"SetReportTitle", Stub1},
    {"SubmitReport", Stub1},
};
static const AscLua::Reg C_BuildCreator_Stubs[] = {
    {"ActivateBuild", Stub1},
    {"AddArmorType", Stub1},
    {"AddRandomEnchant", Stub1},
    {"AddSpell", Stub1},
    {"AddWeaponType", Stub1},
    {"BookmarkBuild", Stub0},
    {"CanActivateBuild", Stub1},
    {"CanAddArmorType", Stub1},
    {"CanAddRandomEnchant", Stub1},
    {"CanAddSpell", Stub1},
    {"CanAddWeaponType", Stub1},
    {"CanDeactivateBuild", Stub1},
    {"CanPublishBuild", Stub2},
    {"CanRemoveArmorType", Stub1},
    {"CanRemoveRandomEnchant", Stub2},
    {"CanRemoveSpell", Stub2},
    {"CanRemoveWeaponType", Stub1},
    {"CanSetArmorTypeComment", Stub1},
    {"CanSetEnchantFlags", Stub2},
    {"CanSetEnchantLevel", Stub2},
    {"CanSetIsCoreAbility", Stub2},
    {"CanSetIsEmpoweringAbility", Stub2},
    {"CanSetIsOptimalAbility", Stub2},
    {"CanSetIsSynergisticAbility", Stub2},
    {"CanSetRandomEnchantComment", Stub1},
    {"CanSetRandomEnchantStacks", Stub2},
    {"CanSetSpellComment", Stub1},
    {"CanSetSpellFlags", Stub2},
    {"CanSetSpellLevel", Stub2},
    {"CanSetWeaponTypeComment", Stub1},
    {"DeactivateBuild", Stub1},
    {"DeleteBuild", Stub1},
    {"DiscardPendingBuild", Stub0},
    {"DoesBuildHaveEnchant", Stub1},
    {"DoesBuildHaveSpellID", Stub1},
    {"EditBuild", Stub0},
    {"ExportBuild", Stub1},
    {"ExportPendingBuild", Stub1},
    {"GetActiveBuild", Stub1},
    {"GetActiveSpecForBuild", Stub1},
    {"GetBookmarkedBuildAtIndex", Stub1},
    {"GetBuild", Stub1},
    {"GetBuildAtIndex", Stub1},
    {"GetEssenceForLevel", Stub4},
    {"GetFilteredEntryAtIndex", Stub1},
    {"GetNumBookmarkedBuilds", StubZero},
    {"GetNumBuilds", Stub1},
    {"GetNumFilteredEntries", Stub1},
    {"GetPendingBuild", Stub1},
    {"GetQualityInfo", Stub0},
    {"GetQualityInfoForLevel", Stub5},
    {"GetSpell", Stub1},
    {"GetSpellByID", Stub1},
    {"ImportBuild", Stub0},
    {"ImportCurrentBuild", Stub0},
    {"IsOwnedBuild", Stub1},
    {"IsUpvotedBuild", Stub1},
    {"PublishBuild", Stub1},
    {"QueryAllBuilds", Stub1},
    {"QueryBuild", Stub1},
    {"RateBuild", Stub1},
    {"RemoveArmorType", Stub1},
    {"RemoveRandomEnchant", Stub2},
    {"RemoveSpell", Stub2},
    {"RemoveWeaponType", Stub1},
    {"SetCategory", Stub0},
    {"SetComment", Stub0},
    {"SetDescription", Stub0},
    {"SetDifficultyRating", Stub2},
    {"SetEnchantFlags", Stub2},
    {"SetEnchantLevel", Stub2},
    {"SetFilteredEntries", Stub0},
    {"SetIcon", Stub0},
    {"SetIsCoreAbility", Stub0},
    {"SetIsEmpoweringAbility", Stub0},
    {"SetIsOptimalAbility", Stub0},
    {"SetIsSynergisticAbility", Stub0},
    {"SetName", Stub0},
    {"SetPrimaryStat", Stub0},
    {"SetRoles", Stub0},
    {"SetSpellFlags", Stub0},
    {"SetSpellLevel", Stub2},
    {"UpdateFilter", Stub0},
};
static const AscLua::Reg C_BuildDraft_Stubs[] = {
    {"GetDraftableBuild", Stub1},
    {"GetDraftedBuild", Stub1},
    {"GetNumDraftableBuilds", Stub1},
    {"IsAwaitingRolePrompt", Stub1},
    {"IsCompletedBuild", Stub1},
    {"IsDraftableBuild", Stub1},
    {"IsDraftedBuild", Stub1},
    {"SelectRole", Stub1},
};
static const AscLua::Reg C_Callboard_Stubs[] = {
    {"GetView", Stub1},
    {"RequestView", Stub1},
};
static const AscLua::Reg C_CallboardCache_Stubs[] = {
    {"GetCallboardCacheInfo", Stub2},
    {"GetCurrentPoints", Stub2},
    {"GetItemLevelInfo", Stub3},
    {"GetPointsForQuest", Stub1},
};
static const AscLua::Reg C_Challenge_Stubs[] = {
    {"CanActivateChallenge", Stub2},
    {"CanDeactivateChallenge", Stub1},
    {"CanResurrect", Stub1},
    {"GetActiveChallenges", Stub1},
    {"GetAllChallenges", Stub1},
    {"GetAllTrials", Stub1},
    {"GetBrokenChallengeRules", Stub1},
    {"GetChallengeAtIndex", Stub1},
    {"GetChallengeCompletion", Stub1},
    {"GetChallengeCompletions", Stub1},
    {"GetChallengeCriteriaInfo", Stub1},
    {"GetChallengeCriterias", Stub1},
    {"GetChallengeFailure", Stub1},
    {"GetChallengeFailures", Stub1},
    {"GetChallengeIDByIndex", Stub1},
    {"GetChallengeInfo", Stub1},
    {"GetChallengeInfoByLevel", Stub1},
    {"GetChallengeLevels", Stub3},
    {"GetChallengesWithGroupID", Stub1},
    {"GetCompletedChallenges", Stub1},
    {"GetConditionLocalization", Stub1},
    {"GetModifierLocalization", Stub1},
    {"GetNumChallenges", Stub1},
    {"GetPendingChallenges", StubTable},
    {"GetRequirementLocalization", Stub1},
    {"GetRuleLocalization", Stub1},
    {"HasBrokenChallengeRule", Stub1},
    {"HasChallengeRule", Stub1},
    {"IsChallengeActive", Stub2},
    {"QueryChallengeCompletions", Stub1},
    {"QueryChallengeFailures", Stub1},
    {"SendChallengeSyncResponse", Stub1},
    {"SetChallengeFilter", Stub0},
    {"StartChallenge", Stub1},
    {"StopChallenge", Stub1},
};

// ---- GetClassInfo -------------------------------------------------------------------------------
// Transcribed from ghidra-ext/out/bindings/GetClassInfo.c (handler_GetClassInfo @ 0x100D8FA0).
// The CoA 21-class picker needs it: CharacterCreate.lua:1741 does
//   className, classFile, enabled = GetClassInfo(classID)
// inside `for i = 1, 21 do ... COA_CLASS_ORDER[i] ... C_CharacterCreate.CanCreateClass(classID)`.
//
// The original: fetch the id argument, look it up via FUN_100b13c0 (the ChrClasses.dbc container at
// 0xAD3404, same shape as every other DBC lookup here), and on a miss push three nils and return 3.
// On a hit it pushes record[4] and record[7] as strings -- Name and Filename once the client's loaded
// record collapses each localised string to a single pointer -- then record[0], the class id, as the
// third value (the Lua caller names it `enabled` and only tests the first two for nil).
static int Asc_GetClassInfo(lua_State* L)
{
    const uint32_t classId = (uint32_t)(int)lua_tonumber(L, 1);
    const char* name = nullptr;
    const char* file = nullptr;
    uint32_t id = 0;
    bool found = false;

    __try
    {
        uint32_t row = DbcRow(kChrClassesDbc, classId);
        if (row)
        {
            found = true;
            name = SafeStr(reinterpret_cast<const char**>(row)[4]);   // Name
            file = SafeStr(reinterpret_cast<const char**>(row)[7]);   // Filename
            id   = reinterpret_cast<uint32_t*>(row)[0];               // ID
        }
    }
    __except (EXCEPTION_EXECUTE_HANDLER)
    {
        AscLog::Printf("GetClassInfo(%u): faulted reading ChrClasses", classId);
        found = false;
    }

    if (!found || !name || !file)
    {
        lua_pushnil(L); lua_pushnil(L); lua_pushnil(L);
        return 3;
    }
    lua_pushstring(L, name);
    lua_pushstring(L, file);
    lua_pushnumber(L, (double)id);
    return 3;
}


// ---- SuggestInvite ------------------------------------------------------------------------------
// Transcribed from ghidra-ext/out/bindings/SuggestInvite.c (FUN_10274610). FrameXML's
// GlobalFunctions.lua:230 does hooksecurefunc("SuggestInvite", ...) at load, and ChatFrame.lua /
// UnitPopup.lua call it -- so a nil here fails the hook and takes the rest of that file with it.
// Wire format: CMSG 0x584 with an lpstring (u32 length, then that many bytes, no NUL) -- the same
// string convention as FUN_100d3680 on the receive side.
static int Asc_SuggestInvite(lua_State* L)
{
    const char* name = lua_isstring(L, 1) ? tostring(L, 1) : nullptr;
    if (!name || !*name)
        return 0;

    uint32_t len = 0;
    while (name[len]) ++len;

    CDataStore pkt{};
    CDataStore::GenPacket(&pkt);
    CDataStore::PutInt32(&pkt, 0x584);
    CDataStore::PutInt32(&pkt, (int32_t)len);
    for (uint32_t i = 0; i < len; ++i)
        CDataStore::PutInt8(&pkt, (int8_t)name[i]);
    pkt.m_read = 0;
    ClientServices::SendPacket(&pkt);
    CDataStore::Release(&pkt);

    AscLog::Printf("SuggestInvite('%s') -> CMSG 0x584", name);
    lua_pushboolean(L, 1);
    return 1;
}

// ---- C_CharacterAdvancement.GetAllEntries -------------------------------------------------------
// Backed by DBFilesClient\CharacterAdvancement.dbc via AscCharacterAdvancement.cpp. PARTIAL --
// authoritative columns only (ids, spells, level, group, class type, tab, costs); the layout fields
// the Lua also reads are absent because nothing maps them. See that file.
//
// FrameXML\Data\CharacterAdvancement.lua:66 does
//   for _, data in ipairs(C_CharacterAdvancement.GetAllEntries()) do
// and the stub returned nil, so the file aborted at line 66 of 142 and everything it defines after
// that was lost. An empty table lets the file load cleanly with no CA data, which is strictly better
// than a hard error -- but the CA tree WILL be empty until this is implemented for real.
//
// Doing it properly means reading CharacterAdvancement.dbc and emitting one table per row with the
// fields the Lua reads: ID, Class, Tab, Flags, Spells, Type, ParentNode, Distance, Color, Anchor,
// NodeType, DraftRequired_XOR, RequiredIDs, PositionX/Y, Masteries. The column mapping is only
// partly known (spell chain [5..9], level [28], class type [32]); the rest should come from the
// decompiled serializer FUN_10172df0, which is what the real binding uses to build this table.
// Guessing the indices would produce a plausible but wrong talent tree, so it is left undone.
static int Asc_CA_GetAllEntries(lua_State* L)
{
    return ::AscCA_GetAllEntries(L);
}

static const AscLua::Reg C_CharacterAdvancement_Stubs[] = {
    {"ActivateLoadout", Stub1},
    {"AddByEntryID", Stub0},
    {"AddSuggestionContextOverride", Stub0},
    {"ApplyPendingBuild", Stub0},
    {"CanAddByEntryID", Stub0},
    {"CanApplyPendingBuild", Stub1},
    {"CanClearPendingBuild", Stub0},
    {"CanLearnID", Stub1},
    {"CanRemoveByEntryID", Stub0},
    {"CanSwapEntriesByID", Stub1},
    {"CanSwitchActiveChrSpec", Stub2},
    {"CanUnlearnAllSpells", Stub2},
    {"CanUnlearnAllTalents", Stub2},
    {"CanUnlearnID", Stub1},
    {"CanUseBrowser", Stub1},
    {"CancelPendingBuild", Stub0},
    {"ClearPendingBuild", Stub0},
    {"ClearPendingBuildByTab", Stub0},
    {"ClearRecentlyLearnedEntries", Stub0},
    {"ClearSuggestionContextOverrides", Stub0},
    {"GetAbilityEssenceCost", Stub1},
    {"GetActiveChrSpec", Stub1},
    {"GetActiveSpecID", Stub1},
    {"GetAllEntries", Asc_CA_GetAllEntries},
    {"GetCategories", Stub1},
    {"GetCategoryDisplayInfo", Stub5},
    {"GetClassAEInvestment", Stub1},
    {"GetClassInfo", Asc_GetClassInfo},
    {"GetClassName", Stub1},
    {"GetClassPointInvestment", Stub1},
    {"GetClassTEInvestment", Stub1},
    {"GetEntriesAvailableForSwap", Stub0},
    {"GetEntriesAvailableForSwapInClass", Stub0},
    {"GetEntriesAvailableForTrade", Stub1},
    {"GetEntriesByClass", Stub1},
    {"GetEntryByInternalID", Stub1},
    {"GetEntryBySpellID", Stub1},
    {"GetExpectedAE", Stub1},
    {"GetExpectedTE", Stub1},
    {"GetFilteredEntryAtIndexByCategory", Stub2},
    {"GetGlobalAEInvestment", Stub1},
    {"GetGlobalTEInvestment", Stub1},
    {"GetImplicitByClass", StubTable},
    {"GetInspectInfo", Stub1},
    {"GetInspectedBuild", Stub1},
    {"GetInternalID", Stub1},
    {"GetKnownSpellEntries", StubTable},
    {"GetKnownSpellEntriesForClass", Stub1},
    {"GetKnownSpells", StubTable},
    {"GetKnownTalentEntries", StubTable},
    {"GetKnownTalentEntriesForClass", Stub1},
    {"GetLearnedAE", StubZero},
    {"GetLearnedTE", StubZero},
    {"GetLowestInvestmentRequired", Stub2},
    {"GetMasteriesByClass", StubTable},
    {"GetNumFilteredEntriesByCategory", Stub1},
    {"GetPendingClassAEInvestment", Stub1},
    {"GetPendingClassPointInvestment", Stub1},
    {"GetPendingClassTEInvestment", Stub1},
    {"GetPendingExpectedAE", Stub1},
    {"GetPendingExpectedTE", Stub1},
    {"GetPendingGlobalAEInvestment", Stub1},
    {"GetPendingGlobalTEInvestment", Stub1},
    {"GetPendingRankByEntryID", Stub2},
    {"GetPendingRemainingAE", Stub1},
    {"GetPendingRemainingTE", Stub1},
    {"GetPendingSummary", Stub1},
    {"GetPendingTabAEInvestment", Stub1},
    {"GetQualityCount", Stub1},
    {"GetQualityLimit", Stub1},
    {"GetRemainingAE", Stub1},
    {"GetRemainingTE", Stub1},
    {"GetRootSpellTagTypes", Stub1},
    {"GetSpellTagTypeDisplayInfo", Stub3},
    {"GetSpellTagTypes", Stub1},
    {"GetSpellsByClass", StubTable},
    {"GetSuggestedStats", Stub2},
    {"GetTabAEInvestment", Stub2},
    {"GetTabName", Stub1},
    {"GetTabTEInvestment", Stub1},
    {"GetTalentEssenceCost", Stub1},
    {"GetTalentRankByID", Stub2},
    {"GetTalentRankBySpellID", Stub2},
    {"GetTalentsByClass", StubTable},
    {"HasAnySuggestionContextOverrides", Stub1},
    {"ImportPendingBuild", Stub1},
    {"ImportPendingBuildID", Stub1},
    {"InspectUnit", Stub1},
    {"IsAbilityID", Stub1},
    {"IsAbilitySpellID", Stub1},
    {"IsActiveBuildAvailable", Stub1},
    {"IsConnectionAllowed", Stub1},
    {"IsFiltered", Stub1},
    {"IsKnownID", Stub1},
    {"IsKnownSpellID", Stub1},
    {"IsLockedID", Stub1},
    {"IsMastery", Stub1},
    {"IsPending", Stub1},
    {"IsPendingBuildAvailable", Stub1},
    {"IsPendingEntryID", Stub1},
    {"IsSpellIDKnown", Stub1},
    {"IsSuggestionContextOverride", Stub1},
    {"IsTalentAbilityID", Stub1},
    {"IsTalentAbilitySpellID", Stub1},
    {"IsTalentID", Stub1},
    {"IsTalentSpellID", Stub1},
    {"KnowsConnectedNodesFor", Stub1},
    {"LearnID", Stub1},
    {"LockID", Stub1},
    {"MeetsInvestmentForAddByEntryID", Stub0},
    {"PickupSpell", Stub0},
    {"RemoveByEntryID", Stub0},
    {"RemoveSuggestionContextOverride", Stub0},
    {"SetFilteredEntriesByCategory", Stub0},
    {"SetLoadoutName", Stub1},
    {"SetLoadoutSortOrder", Stub1},
    {"ShouldConfirmLearnID", Stub1},
    {"ShouldConfirmUnlearnAllSpells", Stub1},
    {"ShouldConfirmUnlearnAllTalents", Stub1},
    {"ShouldConfirmUnlearnID", Stub1},
    {"SwapEntriesByID", Stub0},
    {"SwitchActiveChrSpec", Stub0},
    {"UnitKnownID", Stub1},
    {"UnitTalentRankByID", Stub1},
    {"UnlearnAllSpells", Stub1},
    {"UnlearnAllTalents", Stub1},
    {"UnlearnID", Stub1},
    {"UnlockID", Stub1},
};
static const AscLua::Reg C_CharacterCustomizationUnlocks_Stubs[] = {
    {"GetCurrentOptionInfo", Stub3},
    {"GetFirstLockedRequirement", Stub1},
    {"HasLockedSelections", Stub1},
};
static const AscLua::Reg C_Chat_Stubs[] = {
    {"AcknowledgeChatInfraction", Stub1},
    {"GetChatInfraction", Stub3},
    {"HasChatInfraction", Stub1},
};
static const AscLua::Reg C_CollectorCache_Stubs[] = {
    {"GetCollectorCacheItemInfo", Stub5},
    {"GetCollectorCacheItems", Stub1},
    {"GetCollectorCacheRarityRatesInfo", Stub0},
    {"GetCollectorCacheRarityTypeInfo", Stub2},
    {"GetCollectorCacheTypeInfo", Stub5},
    {"GetNumCollectorCacheItems", Stub1},
    {"OpenCollectorCache", Stub1},
};
static const AscLua::Reg C_Config_Stubs[] = {
    {"GetBoolConfig", Stub1},
    {"GetFloatConfig", Stub1},
    {"GetFloatVectorConfig", Stub1},
    {"GetIntConfig", Stub1},
    {"GetIntVectorConfig", Stub1},
    {"GetRateConfig", Stub1},
};
static const AscLua::Reg C_CustomStore_Stubs[] = {
    {"ApplyCustomStoreFilter", Stub0},
    {"CanPurchaseCustomStoreItem", Stub2},
    {"CanQueryCustomStore", Stub2},
    {"GetCustomStoreData", Stub1},
    {"GetCustomStoreItemInfo", Stub6},
    {"GetCustomStoreMaxPages", Stub1},
    {"GetCustomStoreTypeInfo", Stub2},
    {"IsItemLockedDueToAchievement", Stub1},
    {"IsItemLockedDueToGameEvent", Stub1},
    {"PurchaseCustomStoreItem", Stub1},
    {"QueryCustomStore", Stub1},
};
static const AscLua::Reg C_DraftRewards_Stubs[] = {
    {"CanClaimHandOfFateRewards", Stub2},
    {"ClaimHandOfFateRewards", Stub1},
    {"GetHandOfFateRewardsReleaseInfo", Stub3},
    {"GetLevelingInfo", Stub1},
    {"GetMarkOfAscensionCost", Stub1},
    {"GetNumClaimableHandOfFateRewards", StubZero},
    {"GetNumClaimedHandOfFateRewards", Stub1},
    {"GetRewards", Stub1},
};
static const AscLua::Reg C_ExtraActionButton_Stubs[] = {
    {"GetExtraActionButtonAtIndex", Stub1},
    {"GetExtraActionButtonInfo", Stub4},
    {"GetNumExtraActionButtons", StubZero},
};
static const AscLua::Reg C_Format_Stubs[] = {
    {"Format", Stub1},
};
static const AscLua::Reg C_GMTicket_Stubs[] = {
    {"ApproveAutomatedMessage", Stub1},
    {"AssignGMTicket", Stub1},
    {"CanAssignGMTicket", Stub1},
    {"CanCloseTicket", Stub0},
    {"CanMarkResponseSeen", Stub0},
    {"CanSendTicketMessage", Stub1},
    {"CanSetTicketPriority", Stub1},
    {"CanSetTicketStatus", Stub1},
    {"CanSetTicketTitle", Stub1},
    {"CloseTicket", Stub0},
    {"DeclineAutomatedMessage", Stub1},
    {"GetAutomatedMessage", Stub1},
    {"GetNumSuggestions", Stub0},
    {"GetNumTickets", Stub1},
    {"GetSuggestionAtIndex", Stub0},
    {"GetTicketAtIndex", Stub1},
    {"GetTicketByID", Stub1},
    {"GetTicketMessage", Stub1},
    {"GetTicketMessages", Stub1},
    {"IsResponseSeen", Stub0},
    {"IsTicketAssignedToMe", Stub0},
    {"MarkResponseSeen", Stub0},
    {"SendTicketMessage", Stub1},
    {"SetTicketFilter", Stub0},
    {"SetTicketPriority", Stub1},
    {"SetTicketStatus", Stub1},
    {"SetTicketTitle", Stub1},
};
static const AscLua::Reg C_GroupFinder_Stubs[] = {
    {"CreateListing", Stub1},
    {"GetActivityInfo", Stub4},
    {"GetAvailableActivities", Stub1},
    {"GetAvailableCategories", Stub1},
    {"GetAvailableGroupTypes", Stub1},
    {"GetGroupInfo", Stub1},
    {"GetGroupTypeInfo", Stub1},
    {"GetListedGroupID", Stub1},
    {"GetListedGroups", Stub1},
    {"QueryListedActivities", Stub1},
    {"RemoveListing", Stub1},
    {"RequestInvite", Stub1},
    {"SuggestInvite", Asc_SuggestInvite},
    {"UpdateListing", Stub1},
};
static const AscLua::Reg C_HighRisk_Stubs[] = {
    {"CanToggleFelCommutation", Stub2},
    {"GetInsuranceCostPerSlot", Stub1},
    {"GetInsuranceTotalCost", Stub1},
    {"IsFelCommutationActive", Stub1},
    {"ToggleFelCommutation", Stub1},
};
static const AscLua::Reg C_Item_Stubs[] = {
    {"CanBind", Stub1},
    {"GetScalingLevel", Stub1},
    {"IsBound", Stub1},
};
static const AscLua::Reg C_ItemSet_Stubs[] = {
    {"GetAppearances", StubTable},
    {"GetItemSetNumCollected", Stub2},
    {"GetSetName", Stub1},
};
static const AscLua::Reg C_LootLockout_Stubs[] = {
    {"GetEncounterData", Stub6},
    {"GetEncounterDatasForMapAndDifficulty", StubTable},
    {"GetLootLockoutTimeRemaining", Stub1},
    {"GetLootLockouts", StubTable},
    {"GetUnitEncounterID", Stub1},
    {"GetUnitLootLockForEncounter", Stub1},
    {"HasEncounterDatasForMapAndDifficulty", Stub1},
    {"ListInstanceBinds", StubTable},
    {"QueryInstanceBinds", Stub1},
    {"ResetInstanceDifficulty", Stub1},
};
static const AscLua::Reg C_LoyaltyPass_Stubs[] = {
    {"CanRedeemLoyaltyPassReward", Stub1},
    {"ClaimRewards", Stub0},
    {"GetTimeUntilExpiration", Stub1},
    {"GetTimeUntilNextReward", Stub1},
    {"IsLoyaltyPassActive", Stub1},
    {"IsLoyaltyPassExpired", Stub1},
};
static const AscLua::Reg C_Manastorm_Stubs[] = {
    {"CanEnter", Stub3},
    {"CanLeave", Stub2},
    {"CanSetLoadoutSpellAtIndex", Stub2},
    {"Enter", Stub1},
    {"GetActiveLevel", Stub1},
    {"GetActiveManastormID", Stub1},
    {"GetActiveManastormType", Stub1},
    {"GetAvailableLoadoutSpells", Stub2},
    {"GetBoss", Stub4},
    {"GetEnterableLevels", Stub1},
    {"GetExperienceModifier", Stub2},
    {"GetLoadoutSpellAtIndex", Stub1},
    {"GetManastormCacheInfo", Stub3},
    {"GetMaxCompletedLevels", Stub1},
    {"GetNumLoadoutSlots", Stub1},
    {"GetRewardLimitProgress", Stub5},
    {"GetRewardModifier", Stub6},
    {"GetRewardVisibility", Stub1},
    {"GetStageBonusExperience", Stub2},
    {"IsInManastorm", Stub1},
    {"IsRewardLocked", Stub3},
    {"Leave", Stub1},
    {"SetLoadoutSpellAtIndex", Stub1},
    {"ShowObjectiveIcon", Stub0},
};
static const AscLua::Reg C_MysticEnchant_Stubs[] = {
    {"ApplyItem", Stub1},
    {"ApplySlot", Stub0},
    {"CanApplyAnySlot", Stub2},
    {"CanApplyItem", Stub2},
    {"CanApplySlot", Stub2},
    {"CanCollectionReforgeAnySlot", Stub2},
    {"CanCollectionReforgeItem", Stub6},
    {"CanCollectionReforgeSlot", Stub6},
    {"CanDestroy", Stub2},
    {"CanDisenchantItem", Stub3},
    {"CanDisenchantSlot", Stub3},
    {"CanEquipEnchant", Stub2},
    {"CanEquipItem", Stub2},
    {"CanEquipSlot", Stub2},
    {"CanInspect", Stub1},
    {"CanPurchaseMysticExtract", Stub1},
    {"CanPurchaseMysticScroll", Stub2},
    {"CanReforgeItem", Stub2},
    {"CanReforgeSlot", Stub2},
    {"CanSaveApply", Stub2},
    {"CanSaveCollectionReforge", Stub2},
    {"CollectionReforgeItem", Stub1},
    {"CollectionReforgeSlot", Stub0},
    {"Destroy", Stub1},
    {"DisenchantItem", Stub1},
    {"DisenchantSlot", Stub1},
    {"GetAppliedEnchant", Stub1},
    {"GetApplyChanges", Stub1},
    {"GetApplyItemCost", Stub2},
    {"GetCollectionReforgeChanges", Stub1},
    {"GetCollectionReforgeItemCost", Stub2},
    {"GetCollectionReforgeSlotCost", Stub2},
    {"GetDisenchantCost", Stub2},
    {"GetEnchantInfoByItem", Stub1},
    {"GetEnchantInfoBySpell", Stub1},
    {"GetFilteredMysticScrollAtIndex", Stub1},
    {"GetFilteredMysticScrolls", Stub1},
    {"GetMysticScrollCost", Stub1},
    {"GetMysticScrolls", Stub1},
    {"GetProgress", Stub2},
    {"GetReforgeCost", Stub2},
    {"GetSaveCollectionReforgeSlotCost", Stub2},
    {"HasAnyCollected", Stub1},
    {"HasAnyScroll", Stub1},
    {"HasAnySlotEnchanted", Stub1},
    {"HasNearbyMysticAltar", Stub1},
    {"Inspect", Stub1},
    {"PurchaseMysticExtract", Stub1},
    {"PurchaseMysticScroll", Stub1},
    {"QueryEnchants", Stub1},
    {"ReforgeItem", Stub1},
    {"ReforgeSlot", Stub1},
    {"SaveApply", Stub1},
    {"SaveCollectionReforge", Stub1},
    {"SetMysticScrollFilter", Stub0},
    {"UndoApply", Stub0},
    {"UndoCollectionReforge", Stub0},
    {"UndoLastApply", Stub0},
    {"UndoLastCollectionReforge", Stub0},
};
static const AscLua::Reg C_MysticEnchantPreset_Stubs[] = {
    {"Activate", Stub1},
    {"CanActivate", Stub2},
    {"CanSave", Stub2},
    {"CanUnlock", Stub2},
    {"GetNumPresets", Stub1},
    {"GetPresetData", Stub2},
    {"Unlock", Stub1},
};
static const AscLua::Reg C_MythicPlus_Stubs[] = {
    {"ActivateKeystone", Stub0},
    {"GetActiveKeystoneChampions", Stub1},
    {"GetActiveKeystoneEncounters", Stub1},
    {"GetActiveKeystoneInfo", Stub1},
    {"GetActiveKeystoneTime", Stub2},
    {"GetActiveKeystoneTrash", Stub1},
    {"GetCurrentAffixes", Stub1},
    {"GetKeystoneInfo", Stub1},
    {"GetMapEncounters", Stub1},
    {"GetMapFinalEncounter", Stub1},
    {"IsItemKeystone", Stub1},
    {"IsKeystoneActive", Stub1},
};
static const AscLua::Reg C_PlayerPoll_Stubs[] = {
    {"CanChangeQuestionChoice", Stub1},
    {"CanSubmitAnswer", Stub1},
    {"GetNumQuestionChoices", StubZero},
    {"GetNumQuestions", StubZero},
    {"GetQuestionChoiceInfo", Stub1},
    {"GetQuestionInfo", Stub1},
    {"GetQuestionType", Stub1},
    {"HasUnansweredQuestions", Stub1},
    {"RequestQuestionList", Stub1},
    {"SubmitAnswer", Stub1},
};
static const AscLua::Reg C_PlayerTicket_Stubs[] = {
    {"CanCreateTicket", Stub1},
    {"CanReopenTicket", Stub0},
    {"CreateTicket", Stub1},
    {"GetCurrentTicket", Stub1},
    {"ReopenTicket", Stub0},
};
static const AscLua::Reg C_QuestLog_Stubs[] = {
    {"GetQuestType", Stub1},
    {"GetUnitQuestInfo", Stub1},
    {"GetZoneStoryInfo", Stub2},
};
static const AscLua::Reg C_RecoveryService_Stubs[] = {
    {"GetCategoryItemAtIndex", Stub1},
    {"GetNumItemsInCategory", Stub1},
    {"QueryCategory", Stub1},
    {"RecoverCategoryItemAtIndex", Stub1},
    {"SwapFactionChangePotion", Stub0},
    {"SwapRaceChangePotion", Stub0},
};
static const AscLua::Reg C_Scenario_Stubs[] = {
    {"GetActiveStage", Stub2},
    {"GetEncounterAtIndex", Stub1},
    {"GetNumEncounters", StubZero},
    {"GetScenarioName", Stub1},
    {"IsInScenario", Stub1},
};
static const AscLua::Reg C_SkillCard_Stubs[] = {
    {"GetCardAtIndex", Stub1},
    {"GetCardCount", Stub1},
    {"GetCardID", Stub2},
    {"GetCardRankAtIndex", Stub1},
    {"GetCardSpellID", Stub1},
    {"GetHandOfFateQuests", StubTable},
    {"GetMaxCardCount", StubZero},
    {"GetScrollOfFortuneQuests", StubTable},
    {"GetSkillCardInfo", Stub1},
    {"GetSkillCardInfoAtIndex", Stub1},
    {"GetSkillCardQuality", Stub1},
    {"IsCardAtIndexActive", Stub1},
    {"IsCardAtIndexBlocked", Stub1},
    {"IsCardedID", Stub3},
    {"IsCardedSpellID", Stub3},
    {"RemoveCardAtIndex", Stub1},
    {"SetCardAtIndex", Stub1},
};
static const AscLua::Reg C_SkillCardCollection_Stubs[] = {
    {"CanClaimPendingSkillCardAtIndex", Stub2},
    {"CanPurchaseSealedCard", Stub1},
    {"CanPurchaseSealedCardBoosterPack", Stub2},
    {"ClaimAllPendingSkillCards", Stub0},
    {"ClaimPendingSkillCard", Stub1},
    {"GetBonusSealedCardPacksProgress", StubZero},
    {"GetMaxNumPurchasableSealedCardBoosterPacks", Stub1},
    {"GetMaxRank", Stub1},
    {"GetNumPendingSkillCards", Stub1},
    {"GetNumSkillCards", Stub1},
    {"GetPendingSkillCardAtIndex", Stub3},
    {"GetSealedCardBoosterPackCost", Stub1},
    {"GetSealedCardCost", Stub1},
    {"GetSkillCardAtIndex", Stub1},
    {"HasAnySkillCardsCollected", Stub1},
    {"IsCollected", Stub1},
    {"PurchaseAllSealedCards", Stub0},
    {"PurchaseSealedCard", Stub1},
    {"PurchaseSealedCardBoosterPack", Stub1},
    {"SetSkillCardFilter", Stub0},
};
static const AscLua::Reg C_Spell_Stubs[] = {
    {"AppliesBuff", Stub1},
    {"AppliesDebuff", Stub1},
    {"GetFirstRank", Stub1},
    {"GetMaxLearnableRank", Stub1},
    {"HasRuneUI", Stub1},
    {"IsHarmfulSpell", Stub1},
    {"IsHelpfulSpell", Stub1},
    {"IsImmunitySpell", Stub1},
    {"IsTrainerSpell", Stub1},
};
static const AscLua::Reg C_SpellActivationOverlay_Stubs[] = {
    {"GetSpellActivationOverlayInfo", Stub8},
    {"IsSpellOverlayed", Stub1},
};
static const AscLua::Reg C_Sun_Stubs[] = {
    {"SetX", Stub0},
    {"SetY", Stub0},
    {"SetZ", Stub0},
};
static const AscLua::Reg C_SuperTrack_Stubs[] = {
    {"ClearSuperTracker", Stub0},
    {"GetSuperTrackedPosition", Stub3},
    {"GetSuperTrackedWorldPosition", Stub4},
    {"GetTargetState", Stub1},
    {"IsSuperTrackingAnything", Stub1},
    {"PositionFrame", Stub0},
    {"SetSuperTrackedCorpse", Stub0},
    {"SetSuperTrackedPosition", Stub0},
    {"SetSuperTrackedQuestID", Stub0},
};
static const AscLua::Reg C_Taxi_Stubs[] = {
    {"GetCurrentTaxiNodeID", Stub1},
    {"GetTaxiNodeID", Stub1},
    {"GetTaxiPathDuration", Stub1},
};
static const AscLua::Reg C_TemporalContracts_Stubs[] = {
    {"ActivateAllTemporalContracts", Stub1},
    {"ActivateAllTemporalContractsByContentType", Stub1},
    {"ActivateTemporalContract", Stub1},
    {"GetCategoryData", Stub1},
    {"GetCategoryName", Stub1},
    {"GetCompletableQuestsByCategory", Stub1},
    {"GetCompletableTemporalContracts", Stub1},
    {"GetQuestCategory", Stub1},
    {"GetQuestSortIDs", Stub1},
    {"GetQuestSortText", Stub1},
    {"GetTemporalContractInfo", Stub1},
    {"GetTemporalContractTypes", Stub1},
    {"GetTotalContentTypeCost", Stub1},
    {"GetTotalContentTypeRewards", Stub1},
    {"GetTotalContractTypeCost", Stub1},
    {"GetTotalContractTypeRewards", Stub1},
};
static const AscLua::Reg C_Token_Stubs[] = {
    {"GetTokenAmount", Stub1},
    {"GetTokenInfo", Stub1},
    {"GetTokenTypes", Stub1},
};
static const AscLua::Reg C_TradeSkill_Stubs[] = {
    {"GetCraftedItem", Stub1},
    {"GetReagentItems", Stub1},
};
static const AscLua::Reg C_TrialCreator_Stubs[] = {
    {"ActivateTrial", Stub1},
    {"CanActivateTrial", Stub1},
    {"CanDeactivateTrial", Stub2},
    {"CanEditTrial", Stub1},
    {"CanSaveTrial", Stub1},
    {"DeactivateTrial", Stub1},
    {"DeleteTrial", Stub1},
    {"GetActiveTrial", Stub1},
    {"GetNumTrials", Stub1},
    {"GetOwnedTrials", Stub1},
    {"GetTrialAtIndex", Stub1},
    {"GetTrialCompletion", Stub1},
    {"GetTrialCompletions", Stub1},
    {"GetTrialIDByIndex", Stub1},
    {"GetTrialInfo", Stub1},
    {"QueryTrialCompletions", Stub1},
    {"QueryTrials", Stub1},
    {"RateTrial", Stub1},
    {"SaveTrial", Stub1},
    {"SetTrialFilter", Stub0},
};
static const AscLua::Reg C_Tutorial_Stubs[] = {
    {"GetCategories", StubTable},
    {"AddMentorSpecialization", Stub0},
    {"AnyUnclaimedRewards", Stub3},
    {"CanCollectReward", Stub1},
    {"CanToggleMentorStatus", Stub2},
    {"CollectReward", Stub1},
    {"DebugTutorialAppliccability", Stub1},
    {"GetAvailableMentorAtIndex", Stub6},
    {"GetCategoryProgress", Stub3},
    {"GetIndexByKeywordID", Stub1},
    {"GetKeywordAtIndex", Stub0},
    {"GetKeywordID", Stub1},
    {"GetKeywordInfo", Stub0},
    {"GetMentorSpecializationActive", Stub1},
    {"GetMentorSpecializationInfo", Stub2},
    {"GetMentorSpecializations", StubTable},
    {"GetNumAvailableMentors", Stub1},
    {"GetNumKeywords", Stub1},
    {"GetNumTutorials", StubZero},
    {"GetObjectiveInfo", Stub1},
    {"GetObjectives", StubTable},
    {"GetTutorialAtIndex", Stub0},
    {"GetTutorialByID", Stub0},
    {"GetTutorialDisplay", Stub3},
    {"GetTutorialsRequiredForMentorStatus", Stub1},
    {"IsCategoryEnabled", Stub1},
    {"IsMentorStatusActive", Stub1},
    {"IsRewardCollected", Stub1},
    {"IsTutorialAvailable", Stub2},
    {"IsTutorialComplete", Stub1},
    {"QueryActiveMentors", Stub1},
    {"RemoveMentorSpecialization", Stub0},
    {"SetAvailableMentorFilter", Stub0},
    {"SetKeywordFilter", Stub0},
    {"SetTutorialFilter", Stub0},
    {"StartQuest", Stub1},
    {"ToggleMentorStatus", Stub1},
};
static const AscLua::Reg C_UICamera_Stubs[] = {
    {"GetCameraInfo", Stub5},
    {"GetItemCameraID", Stub1},
};
static const AscLua::Reg C_VanityCollection_Stubs[] = {
    {"GetAllItems", Stub1},
    {"GetDPPrice", Stub1},
    {"GetItem", Stub1},
    {"GetItemByLearnedSpell", Stub1},
    {"GetOwnerByContentItem", Stub1},
    {"GetRandomItem", Stub1},
    {"GetSeasonalShowcaseItems", Stub1},
    {"GetVPPrice", Stub1},
    {"IsCollectionItemOwned", Stub1},
    {"IsConsolidatedVanityBuff", Stub1},
    {"IsOwned", Stub1},
    {"IsPurchaseInProgress", Stub0},
    {"Purchase", Stub1},
    {"PurchaseCollectionItem", Stub0},
    {"PurchaseWebShopItem", Stub1},
    {"QueryItems", Stub1},
    {"RequestDelivery", Stub0},
};
static const AscLua::Reg C_Wildcard_Stubs[] = {
    {"AddAllDesiredFilter", Stub0},
    {"AddAllUndesiredFilter", Stub0},
    {"AddDesiredID", Stub0},
    {"AddUndesiredID", Stub0},
    {"CanAddDesiredID", Stub1},
    {"CanAddUndesiredID", Stub1},
    {"CanRepurchaseAbilityRolls", Stub2},
    {"CanRepurchaseAnyRolls", Stub1},
    {"CanRepurchaseRolls", Stub2},
    {"CanRepurchaseTalentRolls", Stub2},
    {"CanResetAbilities", Stub1},
    {"CanRollAbilities", Stub1},
    {"CanShowStartingChoice", Stub1},
    {"CanStartRapidRolling", Stub2},
    {"CanUseRapidRolling", Stub2},
    {"CancelRapidRolling", Stub2},
    {"ClearDesiredSpells", Stub0},
    {"ClearUndesiredSpells", Stub0},
    {"ContinueRapidRolling", Stub2},
    {"GetFilteredDesiredEntryAtIndex", Stub0},
    {"GetFilteredUndesiredEntryAtIndex", Stub0},
    {"GetMaxRepurchasableAbilityRolls", Stub1},
    {"GetMaxRepurchasableRolls", Stub1},
    {"GetMaxRepurchasableTalentRolls", Stub1},
    {"GetMaximumRapidRolls", Stub1},
    {"GetNextUnlearnedID", Stub1},
    {"GetNumFilteredDesiredEntries", Stub1},
    {"GetNumFilteredUndesiredEntries", Stub1},
    {"GetNumRepurchasableAbilityRolls", Stub1},
    {"GetNumRepurchasableRolls", Stub1},
    {"GetNumRepurchasableTalentRolls", Stub1},
    {"GetRapidRollAbilityBreakpointInfo", Stub3},
    {"GetRapidRollTalentBreakpointInfo", Stub3},
    {"GetRapidRollingState", Stub1},
    {"GetRepurchaseAbilityRollCost", Stub1},
    {"GetRepurchaseRollCost", Stub1},
    {"GetRepurchaseTalentRollCost", Stub1},
    {"GetRollIcons", Stub1},
    {"GetStartingChoiceEntries", Stub1},
    {"IsAwaitingRapidRollingTalentUpgradeRoll", Stub1},
    {"IsDesiredID", Stub1},
    {"IsRapidRollingEnabled", Stub1},
    {"IsRollRequestBlocked", Stub1},
    {"IsUndesiredID", Stub1},
    {"RemoveAllUndesiredAbilities", Stub0},
    {"RemoveAllUndesiredTalents", Stub0},
    {"RemoveDesiredID", Stub0},
    {"RemoveUndesiredID", Stub0},
    {"RepurchaseAbilityRolls", Stub1},
    {"RepurchaseRolls", Stub1},
    {"RepurchaseTalentRolls", Stub1},
    {"RerollUnlockedStartingAbilities", Stub1},
    {"ResetAbilities", Stub1},
    {"RollAbilities", Stub1},
    {"SetFilteredDesiredEntries", Stub0},
    {"SetFilteredUndesiredEntries", Stub0},
    {"StartRapidRolling", Stub2},
    {"UnlearnAbility", Stub1},
    {"WillRollFirstNonStartingAbility", Stub1},
    {"WillRollStartingAbilities", Stub1},
};
static const AscLua::Reg C_WildcardRewards_Stubs[] = {
    {"CanClaimScrollOfFortuneRewards", Stub2},
    {"ClaimScrollOfFortuneRewards", Stub1},
    {"GetNumClaimableScrollOfFortuneRewards", StubZero},
    {"GetNumClaimedScrollOfFortuneRewards", Stub1},
    {"GetScrollOfFortuneLimits", Stub1},
    {"GetScrollOfFortuneRewardsReleaseInfo", Stub3},
};
static const AscLua::Reg C_WorldMap_Stubs[] = {
    {"GetVisiblePOI", StubTable},
    {"GetMapFileByAreaID", Stub1},
    {"GetMapFileByZoneID", Stub1},
    {"GetMapIDByAreaID", Stub1},
    {"GetMapIDByZoneID", Stub1},
    {"GetMapPosition", Stub1},
    {"GetWorldPosition", Stub1},
    {"GetZoneIDByAreaID", Stub1},
};


// ---- GetCustomGameMode / GetJsonCacheCategory ---------------------------------------------------
// Both were Stub1 (nil), and both feed code that immediately uses the result as a number or a table.
//
// GetCustomGameMode: C_GameMode.lua:31 does `local activeModes = GetCustomGameMode()` then
// `bit.contains(activeModes, value)` for every Enum.GameMode -- nil there is the
// "bit.lua:27: bad argument #1 to 'band'" seen in world. Returning 0 is not a placeholder: it is
// Enum.GameMode.None, and it is the accurate value for this realm. The enum covers per-CHARACTER
// custom modes (Random, Ironman, Draft, WildCard, Felforged ...); Conquest of Azeroth is a REALM
// mode in the separate Enum.RealmGameMode, so no custom mode is active here. If we ever run a draft
// or wildcard realm this must come from the real state instead (the original reads an internal
// object via FUN_1031EF10 and masks off 0x800).
static int Asc_GetCustomGameMode(lua_State* L)
{
    lua_pushnumber(L, 0.0);     // Enum.GameMode.None
    return 1;
}

// GetJsonCacheCategory: MapPOI.lua:72 does `pairs(GetJsonCacheCategory("AREA_POI_PAYLOAD"))`.
// An empty table is the truthful answer while nothing populates the client's JSON cache -- the
// payloads arrive from the server and ours does not send them.
static int Asc_GetJsonCacheCategory(lua_State* L)
{
    lua_createtable(L, 0, 0);
    return 1;
}

static const AscLua::Reg BareStubs[] = {
    // RaidProfiles.lua:826 does pairs() on this. Not a client native and not registered
    // anywhere, so it was nil.
    {"GetRaidProfileFlattenedOptions", StubTable},
    // 2026-09-22 sweep: these are registered inside a C_* namespace by the generator, but the
    // UI calls them BARE (comments stripped before scanning; names the client registers
    // natively, and names the UI defines in Lua, were excluded so we never shadow a real one).
    {"GetEncounterDatasForMapAndDifficulty", StubTable},
    {"GetHandOfFateQuests", StubTable},
    {"GetLootLockouts", StubTable},
    {"GetScrollOfFortuneQuests", StubTable},
    {"GetUnitEncounterID", Stub1},
    {"GetUnitLootLockForEncounter", Stub1},
    {"IsSpellIDKnown", Stub1},
    {"RequestInvite", Stub1},
    {"AbandonSkillID", Stub0},
    {"AcceptAllAvailableGossipQuests", Stub0},
    {"AcceptAvailableGossipQuest", Stub0},
    {"AddAutoQuestPopUp", Stub1},
    {"Ascension_GetArenaBracketCutoffs", Stub1},
    {"CA_GetCreditAmount", Stub1},
    {"CanJoinRatedArenaWithoutGroup", Stub1},
    {"CanShowAchievementToast", Stub1},
    {"CanToggleBuildDraftMode", Stub1},
    {"CanToggleCrusaderMode", Stub1},
    {"CanToggleDraftMode", Stub1},
    {"CanToggleFelforgedMode", Stub2},
    {"CanToggleIronmanMode", Stub1},
    {"CanToggleNightmareMode", Stub1},
    {"CanToggleResoluteMode", Stub1},
    {"CanToggleSurvivalistMode", Stub1},
    {"CanToggleWildCardMode", Stub1},
    {"CancelHandOfFateSelection", Stub0},
    {"CastSpecialSpell", Stub0},
    {"CharacterActivate", Stub0},
    {"CharacterDeactivate", Stub0},
    {"ClearPacket", Stub0},
    {"ClientsideAura", Stub0},
    {"ClientsideAuraCreature", Stub0},
    {"ClientsideAuraTarget", Stub0},
    {"CombatLogDisable", Stub0},
    {"CombatLogDisableAll", Stub0},
    {"CompleteActiveGossipQuest", Stub0},
    {"CompleteAllActiveGossipQuests", Stub0},
    {"ConvertToParty", Stub0},
    {"CreateDBC", Stub1},
    {"CreatePacket", Stub1},
    {"Custom_HandleTerrainClick", Stub0},
    {"Custom_HandleTerrainClick_PlayerPos", Stub0},
    {"Custom_HandleTerrainClick_TargetPos", Stub0},
    {"Custom_SendAutoQuestAccept", Stub0},
    {"DecodeJSON", Stub1},
    {"DecodeJSONContent", Stub1},
    {"DeleteStablePet", Stub0},
    {"DiscordFeaturesEnabled", Stub1},
    {"DiscordFeaturesOverlayEnabled", Stub1},
    {"DiscordOpenGuildInvite", Stub0},
    {"FadeScreen", Stub1},
    {"FriendStatusIsOffline", Stub1},
    {"FriendStatusSetOffline", Stub0},
    {"GM_GetTransactionContent", Stub0},
    {"GM_GetTransactionIdList", Stub1},
    {"GetActiveGossipQuestIds", Stub1},
    {"GetActiveMapID", Stub1},
    {"GetActiveMapName", Stub1},
    {"GetAreaId", Stub1},
    {"GetAreaIdByName", Stub1},
    {"GetAreaName", Stub1},
    {"GetAscensionDonationPoints", StubZero},
    {"GetAscensionSeasonalPoints", Stub1},
    {"GetAuctionHouseDepositMaxVanity", Stub1},
    {"GetAuctionHouseDepositRateVanity", Stub1},
    {"GetAutoQuestPopUp", Stub1},
    {"GetAvailableGossipQuestIds", Stub1},
    {"GetBankPermissions", Stub2},
    {"GetBindPosition", Stub4},
    {"GetCharacterSelectionMailData", Stub2},
    {"GetCheckpointsEnabled", Stub1},
    {"GetClassInfoByName", Stub1},
    {"GetCompleteGossipQuestIds", Stub1},
    {"GetContainerItemGUID", Stub1},
    {"GetCreatureInfoInstant", Stub1},
    {"GetCurrentPlayerPosition", Stub4},
    {"GetCustomAscensionPointValue", Stub1},
    {"GetCustomGameMode", Asc_GetCustomGameMode},
    {"GetDraftModePickCount", Stub1},
    {"GetDraftModePickSpellAtIndex", Stub1},
    {"GetEquipmentSetIDForSpecialization", Stub1},
    {"GetEquipmentSetItemGUIDs", Stub0},
    {"GetFileStreamingStatus", StubZero},
    {"GetFriendsMetadata", Stub1},
    {"GetGameEventInfo", Stub1},
    {"GetGameEventInfos", Stub1},
    {"GetGloryPoints", Stub1},
    {"GetGossipIconOverride", Stub1},
    {"GetHandOfFatePickCount", Stub1},
    {"GetHandOfFatePickSpellAtIndex", Stub1},
    {"GetHandOfFateSacrificePickCount", Stub1},
    {"GetHandOfFateSacrificePickSpellAtIndex", Stub1},
    {"GetHonorableCombatZones", Stub1},
    {"GetInventoryItemGUID", Stub1},
    {"GetItemClassID", Stub1},
    {"GetItemFlavorText", Stub1},
    {"GetItemIconInstant", Stub1},
    {"GetItemInventoryType", Stub1},
    {"GetItemLevelInstant", Stub1},
    {"GetItemName", Stub1},
    {"GetItemPvEPower", Stub1},
    {"GetItemPvPPower", Stub1},
    {"GetItemQuality", Stub1},
    {"GetItemSetID", Stub1},
    {"GetItemSubClassID", Stub1},
    {"GetItemTemplate", Stub1},
    {"GetItemTemplateBonding", Stub1},
    {"GetItemWeaponSpeed", StubZero},
    {"GetKeyringItemGUID", Stub1},
    {"GetKnownAddons", Stub1},
    {"GetLFGBoss", Stub1},
    {"GetLootSpecialization", Stub1},
    {"GetMapID", Stub1},
    {"GetMapName", Stub1},
    {"GetMeleeHaste", Stub1},
    {"GetMysticEnchantPresetIDForSpecialization", Stub1},
    {"GetNamePlateForUnit", Stub1},
    {"GetNumActivePOI", Stub1},
    {"GetNumAutoQuestPopUps", StubZero},
    {"GetPOIInfo", Stub7},
    {"GetPlayerInfo", Stub1},
    {"GetPrestigeLevel", Stub2},
    {"GetQuestLogIndexByID", Stub1},
    {"GetQuestScaling", Stub1},
    {"GetRaceInfo", Stub1},
    {"GetRaceInfoByID", Stub3},
    {"GetRangedWeaponEnchantInfo", Stub3},
    {"GetRealmAuctionCutRate", Stub1},
    {"GetRealmExpansion", Stub1},
    {"GetRealmId", Stub1},
    {"GetRealmMaintenance", Stub1},
    {"GetRealmMaxLevel", Stub1},
    {"GetScreenLocationInfo", Stub1},
    {"GetScreenPosition", Stub1},
    {"GetSeasonalCollectionInfo", Stub1},
    {"GetSelectedHandOfFateSpell", Stub1},
    {"GetServerMaxLevel", Stub1},
    {"GetServerTime", Stub1},
    {"GetServerTimeOffset", Stub1},
    {"GetSkillInfo", Stub6},
    {"GetSpellBaseCooldown", Stub2},
    {"GetSpellBaseDuration", Stub1},
    {"GetSpellCharges", Stub4},
    // hooksecurefunc("SuggestInvite") in GlobalFunctions.lua needs this as a BARE GLOBAL too.
    {"SuggestInvite", Asc_SuggestInvite},
    // CharacterCreate.lua:1741 calls this as a BARE GLOBAL; the generator had only placed it in
    // C_CharacterAdvancement, so the CoA class picker saw a nil and threw.
    {"GetClassInfo", Asc_GetClassInfo},
    {"GetSpellDescription", Stub1},
    {"GetSpellHaste", Stub1},
    {"GetSpellMaxStack", StubZero},
    {"GetStablePetID", Stub1},
    {"GetTitleForQuestID", Stub1},
    {"GetTokenIDsFromGUID", Stub1},
    {"GetUnitPrimaryStat", Stub1},
    {"GetWeaponTempEnchantInfo", Stub2},
    {"GetWildcardPrestigeInfo", Stub3},
    {"GetWorldMapAreaID", Stub1},
    {"GetWorldState", Stub1},
    {"GetZoneId", Stub1},
    {"GetZoneInstanceID", Stub1},
    {"GetZoneInstanceList", Stub1},
    {"GuildQueryPermissions", Stub0},
    {"HasDraftModePick", Stub1},
    {"HasHandOfFatePick", Stub1},
    {"HasHandOfFateSacrificePick", Stub1},
    {"HasVisitedArea52ThisSession", Stub1},
    {"InteractNearest", Stub0},
    {"Internal_CopyToClipboard", Stub0},
    {"IsAbsorbSpell", Stub2},
    {"IsAddOnsAllowed", Stub1},
    {"IsAreaHidden", Stub1},
    {"IsAutoLogin", Stub1},
    {"IsBuildDraftModeEnabled", Stub1},
    {"IsCardSwap", Stub1},
    {"IsCardSwapPick", Stub1},
    {"IsCardSwapPicked", Stub1},
    {"IsCardSwapSacrifice", Stub1},
    {"IsDraftMode", Stub1},
    {"IsGameEventActive", Stub1},
    {"IsKeyDown", Stub1},
    {"IsKnownAddon", Stub1},
    {"IsLibraryLoaded", Stub1},
    {"IsLuckySkillCardDraft", Stub1},
    {"IsLuckySkillCardPick", Stub1},
    {"IsLuckySkillCardPicked", Stub1},
    {"IsMasteryDraft", Stub1},
    {"IsPassiveSpellID", Stub1},
    {"IsQuestComplete", Stub1},
    {"IsSeasonalCollectionUnlocked", Stub1},
    {"IsSkillCardDraft", Stub1},
    {"IsSkillCardPick", Stub1},
    {"IsSkillCardPicked", Stub1},
    {"JoinArenaWithRole", Stub0},
    {"ListCVars", Stub1},
    {"LoadAscensionContentJSON", Stub1},
    {"LoadLibrary", Stub0},
    {"OpenAscensionDBURL", Stub0},
    {"OpenAscensionURL", Stub0},
    {"OpenAscensionWikiURL", Stub0},
    {"PortGraveyard", Stub0},
    {"ReadCustomWTF", Stub1},
    {"RedraftAbilities", Stub1},
    {"RegisterInterfaceEvent", Stub1},
    {"RegisterPacket", Stub0},
    {"RegisterSavedCVar", Stub1},
    {"ReloadItemDisplayInfoCollections", Stub0},
    {"ReloadMap", Stub1},
    {"RemoveAutoQuestPopUp", Stub0},
    {"RequestChangeRuleset", Stub0},
    {"RequestDeliverSeasonalCollectionItem", Stub0},
    {"RequestDeliverVanityCollectionItem", Stub0},
    {"RequestPlayerInfo", Stub1},
    {"RequestRespawnAtCheckpoint", Stub0},
    {"RequestSetDungeonDifficulty", Stub0},
    {"RequestStatisticQuery", Stub0},
    {"ResetDungeons", Stub0},
    {"ResetRaids", Stub0},
    {"ResetWorldTime", Stub0},
    {"RessurectAtCheckpoint", Stub0},
    {"RessurectInClosestCapital", Stub0},
    {"RessurectInClosestTown", Stub0},
    {"SaveSavedVariables", Stub0},
    {"SendDraftModeSpellSelection", Stub0},
    {"SendDraftSkip", Stub0},
    {"SendHandOfFateSacrificeSpellSelection", Stub0},
    {"SendHandOfFateSpellSelection", Stub0},
    {"SendWindowsFlash", Stub0},
    {"SetAFKLogoutTimer", Stub0},
    {"SetAFKTimer", Stub0},
    {"SetAttackAnimation", Stub0},
    {"SetAttackCursor", Stub0},
    {"SetAttackDistance", Stub0},
    {"SetAttackTexture", Stub0},
    {"SetAutoRangedCombatSpell", Stub0},
    {"SetCameraFoV", Stub0},
    {"SetCursorPosition", Stub1},
    {"SetEquipmentSetIDForSpecialization", Stub0},
    {"SetFadeOutGameObjects", Stub0},
    {"SetFriendsMetadata", Stub1},
    {"SetInteractDistance", Stub0},
    {"SetLevelScaling", Asc_SetLevelScaling},
    {"SetLootSpecialization", Stub0},
    {"SetModelApplyComponents", Stub0},
    {"SetMysticEnchantPresetIDForSpecialization", Stub0},
    {"SetNamePlateCastBarMode", Stub0},
    {"SetNamePlateRange", Stub0},
    {"SetNamePlateScaleX", Stub0},
    {"SetNamePlateScaleY", Stub0},
    {"SetPortraitToTexture", Stub1},
    {"SetRangedAttackTexture", Stub0},
    {"SetRenderOcclusion", Stub0},
    // SetVolume: not a global -- a MovieFrame method (AscGlobalsB "#MovieFrame", registrar 0x970610).
    {"SetZoneInstanceID", Stub0},
    {"ShowQuestComplete", Stub0},
    {"SignalEvent", Stub0},
    {"TargetClosestEnemy", Stub0},
    {"TaxiCancelEarlyLanding", Stub0},
    {"TaxiIsEarlyLanding", Stub1},
    {"TaxiRequestEarlyLanding", Stub0},
    {"ToggleBuildDraftMode", Stub1},
    {"ToggleCrusaderMode", Stub1},
    {"ToggleDraftMode", Stub1},
    {"ToggleFelforgedMode", Stub1},
    {"ToggleIronmanMode", Stub1},
    {"ToggleNightmareMode", Stub1},
    {"ToggleResoluteMode", Stub1},
    {"ToggleSurvivalistMode", Stub1},
    {"ToggleWildCardMode", Stub1},
    {"UnitAlternativePower", Stub1},
    {"UnitAlternativePowerMax", Stub1},
    {"UnitAlternativePowerType", Stub1},
    {"UnitAverageItemLevel", Stub1},
    {"UnitCastingSpellID", Stub1},
    {"UnitDistanceSquared", Stub1},
    {"UnitGetTotalAbsorbs", Stub1},
    {"UnitGetTotalHealAbsorbs", Stub1},
    {"UnitGetTotalSchoolAbsorbs", Stub6},
    {"UnitIsLevelScaling", Stub1},
    {"UnitTitle", Stub1},
};

void RegisterAll(lua_State* L)
{
    if (!L) return;
    RegisterNamespace(L, "C_AccountInfo", C_AccountInfo_Stubs, sizeof(C_AccountInfo_Stubs) / sizeof(C_AccountInfo_Stubs[0]));
    RegisterNamespace(L, "C_Appearance", C_Appearance_Stubs, sizeof(C_Appearance_Stubs) / sizeof(C_Appearance_Stubs[0]));
    RegisterNamespace(L, "C_AppearanceCollection", C_AppearanceCollection_Stubs, sizeof(C_AppearanceCollection_Stubs) / sizeof(C_AppearanceCollection_Stubs[0]));
    RegisterNamespace(L, "C_AppearanceOutfit", C_AppearanceOutfit_Stubs, sizeof(C_AppearanceOutfit_Stubs) / sizeof(C_AppearanceOutfit_Stubs[0]));
    RegisterNamespace(L, "C_AssetQueryService", C_AssetQueryService_Stubs, sizeof(C_AssetQueryService_Stubs) / sizeof(C_AssetQueryService_Stubs[0]));
    RegisterNamespace(L, "C_Aura", C_Aura_Stubs, sizeof(C_Aura_Stubs) / sizeof(C_Aura_Stubs[0]));
    RegisterNamespace(L, "C_BugTracker", C_BugTracker_Stubs, sizeof(C_BugTracker_Stubs) / sizeof(C_BugTracker_Stubs[0]));
    RegisterNamespace(L, "C_BuildCreator", C_BuildCreator_Stubs, sizeof(C_BuildCreator_Stubs) / sizeof(C_BuildCreator_Stubs[0]));
    RegisterNamespace(L, "C_BuildDraft", C_BuildDraft_Stubs, sizeof(C_BuildDraft_Stubs) / sizeof(C_BuildDraft_Stubs[0]));
    RegisterNamespace(L, "C_Callboard", C_Callboard_Stubs, sizeof(C_Callboard_Stubs) / sizeof(C_Callboard_Stubs[0]));
    RegisterNamespace(L, "C_CallboardCache", C_CallboardCache_Stubs, sizeof(C_CallboardCache_Stubs) / sizeof(C_CallboardCache_Stubs[0]));
    RegisterNamespace(L, "C_Challenge", C_Challenge_Stubs, sizeof(C_Challenge_Stubs) / sizeof(C_Challenge_Stubs[0]));
    RegisterNamespace(L, "C_CharacterAdvancement", C_CharacterAdvancement_Stubs, sizeof(C_CharacterAdvancement_Stubs) / sizeof(C_CharacterAdvancement_Stubs[0]));
    RegisterNamespace(L, "C_CharacterCustomizationUnlocks", C_CharacterCustomizationUnlocks_Stubs, sizeof(C_CharacterCustomizationUnlocks_Stubs) / sizeof(C_CharacterCustomizationUnlocks_Stubs[0]));
    RegisterNamespace(L, "C_Chat", C_Chat_Stubs, sizeof(C_Chat_Stubs) / sizeof(C_Chat_Stubs[0]));
    RegisterNamespace(L, "C_CollectorCache", C_CollectorCache_Stubs, sizeof(C_CollectorCache_Stubs) / sizeof(C_CollectorCache_Stubs[0]));
    RegisterNamespace(L, "C_Config", C_Config_Stubs, sizeof(C_Config_Stubs) / sizeof(C_Config_Stubs[0]));
    RegisterNamespace(L, "C_CustomStore", C_CustomStore_Stubs, sizeof(C_CustomStore_Stubs) / sizeof(C_CustomStore_Stubs[0]));
    RegisterNamespace(L, "C_DraftRewards", C_DraftRewards_Stubs, sizeof(C_DraftRewards_Stubs) / sizeof(C_DraftRewards_Stubs[0]));
    RegisterNamespace(L, "C_ExtraActionButton", C_ExtraActionButton_Stubs, sizeof(C_ExtraActionButton_Stubs) / sizeof(C_ExtraActionButton_Stubs[0]));
    RegisterNamespace(L, "C_Format", C_Format_Stubs, sizeof(C_Format_Stubs) / sizeof(C_Format_Stubs[0]));
    RegisterNamespace(L, "C_GMTicket", C_GMTicket_Stubs, sizeof(C_GMTicket_Stubs) / sizeof(C_GMTicket_Stubs[0]));
    RegisterNamespace(L, "C_GroupFinder", C_GroupFinder_Stubs, sizeof(C_GroupFinder_Stubs) / sizeof(C_GroupFinder_Stubs[0]));
    RegisterNamespace(L, "C_HighRisk", C_HighRisk_Stubs, sizeof(C_HighRisk_Stubs) / sizeof(C_HighRisk_Stubs[0]));
    RegisterNamespace(L, "C_Item", C_Item_Stubs, sizeof(C_Item_Stubs) / sizeof(C_Item_Stubs[0]));
    RegisterNamespace(L, "C_ItemSet", C_ItemSet_Stubs, sizeof(C_ItemSet_Stubs) / sizeof(C_ItemSet_Stubs[0]));
    RegisterNamespace(L, "C_LootLockout", C_LootLockout_Stubs, sizeof(C_LootLockout_Stubs) / sizeof(C_LootLockout_Stubs[0]));
    RegisterNamespace(L, "C_LoyaltyPass", C_LoyaltyPass_Stubs, sizeof(C_LoyaltyPass_Stubs) / sizeof(C_LoyaltyPass_Stubs[0]));
    RegisterNamespace(L, "C_Manastorm", C_Manastorm_Stubs, sizeof(C_Manastorm_Stubs) / sizeof(C_Manastorm_Stubs[0]));
    RegisterNamespace(L, "C_MysticEnchant", C_MysticEnchant_Stubs, sizeof(C_MysticEnchant_Stubs) / sizeof(C_MysticEnchant_Stubs[0]));
    RegisterNamespace(L, "C_MysticEnchantPreset", C_MysticEnchantPreset_Stubs, sizeof(C_MysticEnchantPreset_Stubs) / sizeof(C_MysticEnchantPreset_Stubs[0]));
    RegisterNamespace(L, "C_MythicPlus", C_MythicPlus_Stubs, sizeof(C_MythicPlus_Stubs) / sizeof(C_MythicPlus_Stubs[0]));
    RegisterNamespace(L, "C_PlayerPoll", C_PlayerPoll_Stubs, sizeof(C_PlayerPoll_Stubs) / sizeof(C_PlayerPoll_Stubs[0]));
    RegisterNamespace(L, "C_PlayerTicket", C_PlayerTicket_Stubs, sizeof(C_PlayerTicket_Stubs) / sizeof(C_PlayerTicket_Stubs[0]));
    RegisterNamespace(L, "C_QuestLog", C_QuestLog_Stubs, sizeof(C_QuestLog_Stubs) / sizeof(C_QuestLog_Stubs[0]));
    RegisterNamespace(L, "C_RecoveryService", C_RecoveryService_Stubs, sizeof(C_RecoveryService_Stubs) / sizeof(C_RecoveryService_Stubs[0]));
    RegisterNamespace(L, "C_Scenario", C_Scenario_Stubs, sizeof(C_Scenario_Stubs) / sizeof(C_Scenario_Stubs[0]));
    RegisterNamespace(L, "C_SkillCard", C_SkillCard_Stubs, sizeof(C_SkillCard_Stubs) / sizeof(C_SkillCard_Stubs[0]));
    RegisterNamespace(L, "C_SkillCardCollection", C_SkillCardCollection_Stubs, sizeof(C_SkillCardCollection_Stubs) / sizeof(C_SkillCardCollection_Stubs[0]));
    RegisterNamespace(L, "C_Spell", C_Spell_Stubs, sizeof(C_Spell_Stubs) / sizeof(C_Spell_Stubs[0]));
    RegisterNamespace(L, "C_SpellActivationOverlay", C_SpellActivationOverlay_Stubs, sizeof(C_SpellActivationOverlay_Stubs) / sizeof(C_SpellActivationOverlay_Stubs[0]));
    RegisterNamespace(L, "C_Sun", C_Sun_Stubs, sizeof(C_Sun_Stubs) / sizeof(C_Sun_Stubs[0]));
    RegisterNamespace(L, "C_SuperTrack", C_SuperTrack_Stubs, sizeof(C_SuperTrack_Stubs) / sizeof(C_SuperTrack_Stubs[0]));
    RegisterNamespace(L, "C_Taxi", C_Taxi_Stubs, sizeof(C_Taxi_Stubs) / sizeof(C_Taxi_Stubs[0]));
    RegisterNamespace(L, "C_TemporalContracts", C_TemporalContracts_Stubs, sizeof(C_TemporalContracts_Stubs) / sizeof(C_TemporalContracts_Stubs[0]));
    RegisterNamespace(L, "C_Token", C_Token_Stubs, sizeof(C_Token_Stubs) / sizeof(C_Token_Stubs[0]));
    RegisterNamespace(L, "C_TradeSkill", C_TradeSkill_Stubs, sizeof(C_TradeSkill_Stubs) / sizeof(C_TradeSkill_Stubs[0]));
    RegisterNamespace(L, "C_TrialCreator", C_TrialCreator_Stubs, sizeof(C_TrialCreator_Stubs) / sizeof(C_TrialCreator_Stubs[0]));
    RegisterNamespace(L, "C_Tutorial", C_Tutorial_Stubs, sizeof(C_Tutorial_Stubs) / sizeof(C_Tutorial_Stubs[0]));
    RegisterNamespace(L, "C_UICamera", C_UICamera_Stubs, sizeof(C_UICamera_Stubs) / sizeof(C_UICamera_Stubs[0]));
    RegisterNamespace(L, "C_VanityCollection", C_VanityCollection_Stubs, sizeof(C_VanityCollection_Stubs) / sizeof(C_VanityCollection_Stubs[0]));
    RegisterNamespace(L, "C_Wildcard", C_Wildcard_Stubs, sizeof(C_Wildcard_Stubs) / sizeof(C_Wildcard_Stubs[0]));
    RegisterNamespace(L, "C_WildcardRewards", C_WildcardRewards_Stubs, sizeof(C_WildcardRewards_Stubs) / sizeof(C_WildcardRewards_Stubs[0]));
    RegisterNamespace(L, "C_WorldMap", C_WorldMap_Stubs, sizeof(C_WorldMap_Stubs) / sizeof(C_WorldMap_Stubs[0]));
    for (auto& g : BareStubs) RegisterGlobalIfMissing(L, g.name, g.fn);
}

} // namespace AscStubs
